import { describe, it, expect, beforeAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, existsSync, mkdirSync, mkdtempSync, writeFileSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { validateScript } from '../../src/cli/validate.js';
import { lintWorkflowSource } from '../../src/cli/lint.js';
import { VERSION } from '../../src/version.js';
import { assertSemver } from '../../scripts/semver.mjs';

const root = join(__dirname, '../..');
// The provenance banner scripts/sync-version.mjs prepends to the generated file.
const BANNER = '// Generated by scripts/sync-version.mjs from package.json — do not edit.\n';

describe('plugin bundles', () => {
  // The bundles are gitignored build outputs — rebuild from the canonical
  // sources so the assertions run against fresh, never stale, copies. The
  // sentinels prove the rebuild wipes prior outputs rather than copying over them.
  beforeAll(() => {
    for (const d of ['dist-codex', 'dist-qoder']) {
      mkdirSync(join(root, d), { recursive: true });
      writeFileSync(join(root, d, 'STALE.txt'), 'stale');
    }
    execFileSync('node', [join(root, 'scripts/build-plugins.mjs')], { stdio: 'pipe' });
  });

  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

  it('codex bundle: valid manifest + README + skill + license present', () => {
    const manifest = JSON.parse(readFileSync(join(root, 'dist-codex/.codex-plugin/plugin.json'), 'utf8'));
    expect(manifest.name).toBe('ultracode');
    expect(manifest.version).toBe(pkg.version);
    expect(existsSync(join(root, 'dist-codex/README.md'))).toBe(true);
    expect(existsSync(join(root, 'dist-codex/skills/ultracode/SKILL.md'))).toBe(true);
    // The manifest declares a license, so the standalone bundle must carry the
    // text — byte-identical to the root LICENSE (a truncated copy must fail).
    expect(readFileSync(join(root, 'dist-codex/LICENSE'), 'utf8')).toBe(readFileSync(join(root, 'LICENSE'), 'utf8'));
  });

  it('qoder bundle: manifest + README + skill + templates + agent defs + license', () => {
    const manifest = JSON.parse(readFileSync(join(root, 'dist-qoder/.qoder-plugin/plugin.json'), 'utf8'));
    expect(manifest.name).toBe('ultracode');
    expect(manifest.version).toBe(pkg.version);
    for (const f of [
      'dist-qoder/README.md',
      'dist-qoder/skills/ultracode/SKILL.md',
      'dist-qoder/workflows/uc-review.workflow.js',
      'dist-qoder/workflows/uc-research.workflow.js',
      'dist-qoder/agents/uc-xhigh.md',
      'dist-qoder/agents/uc-verifier.md',
    ]) {
      expect(existsSync(join(root, f)), f).toBe(true);
    }
    expect(readFileSync(join(root, 'dist-qoder/LICENSE'), 'utf8')).toBe(readFileSync(join(root, 'LICENSE'), 'utf8'));
  });

  it('root LICENSE is the canonical Apache-2.0 text', () => {
    // The bundle assertions compare byte-identity against the root file, so pin
    // the root itself: sha256 of https://www.apache.org/licenses/LICENSE-2.0.txt.
    // A truncated or swapped root LICENSE would otherwise keep everything green.
    const sha = createHash('sha256').update(readFileSync(join(root, 'LICENSE'))).digest('hex');
    expect(sha).toBe('cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30');
  });

  it('license is Apache-2.0 across all mirrors', () => {
    // Same rationale as the version-mirror guard above: the license is declared
    // in package.json, the lockfile root entry, and both bundle manifests — a
    // partial revert (regenerated lockfile, one manifest flipped back) would
    // otherwise ship a manifest that contradicts the bundled LICENSE text.
    expect(pkg.license).toBe('Apache-2.0');
    const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
    expect(lock.packages?.['']?.license).toBe('Apache-2.0');
    for (const m of ['dist-codex/.codex-plugin/plugin.json', 'dist-qoder/.qoder-plugin/plugin.json']) {
      expect(JSON.parse(readFileSync(join(root, m), 'utf8')).license, m).toBe('Apache-2.0');
    }
  });

  it('engine VERSION constant matches package.json', () => {
    expect(VERSION).toBe(pkg.version);
  });

  it('package-lock.json version fields match package.json', () => {
    // npm keeps these in sync during `npm version`, but a hand-edited
    // package.json bypasses that — this guard is what would have caught the
    // drift that commit "sync package-lock.json with the 0.1.2 version bump"
    // had to patch after the fact. Both the top-level and root-package fields
    // are checked because lockfileVersion 3 stores the version in both.
    const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
    expect(lock.version).toBe(pkg.version);
    expect(lock.packages?.['']?.version).toBe(pkg.version);
  });

  it('npm version --no-git-tag-version runs the real hook and stages all three files', () => {
    // Sources the REAL `version` hook from the repo package.json and runs it end
    // to end, so a typo in the actual hook (or its removal) fails here — not just
    // in a hand-copied duplicate. In no-tag mode npm stages nothing itself, so a
    // partial stage (only the mirror) would let a plain commit reintroduce drift;
    // also pins that npm updates the lock BEFORE the hook (staged lock must carry
    // the bump).
    expect(pkg.scripts?.version, 'package.json must define a `version` hook').toBeTruthy();
    const dir = mkdtempSync(join(tmpdir(), 'uc-npmver-'));
    mkdirSync(join(dir, 'src'), { recursive: true });
    mkdirSync(join(dir, 'scripts'), { recursive: true });
    cpSync(join(root, 'scripts/semver.mjs'), join(dir, 'scripts/semver.mjs'));
    cpSync(join(root, 'scripts/sync-version.mjs'), join(dir, 'scripts/sync-version.mjs'));
    writeFileSync(join(dir, 'package.json'), JSON.stringify({
      name: 'uc-npmver-fixture', version: '1.2.3',
      scripts: { version: pkg.scripts.version },
    }, null, 2) + '\n');
    writeFileSync(join(dir, 'package-lock.json'), JSON.stringify({
      name: 'uc-npmver-fixture', version: '1.2.3', lockfileVersion: 3, packages: { '': { version: '1.2.3' } },
    }, null, 2) + '\n');
    writeFileSync(join(dir, 'src/version.ts'), `${BANNER}export const VERSION = '1.2.3';\n`);
    // Hermetic: pin npm + git config so a contributor's global .npmrc
    // (ignore-scripts / package-lock=false) or git config (gpgsign, hooksPath)
    // can't fail this spuriously. Local `git config user.*` below still applies.
    const env = {
      ...process.env,
      npm_config_ignore_scripts: 'false',
      npm_config_package_lock: 'true',
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
    };
    const git = (...a: string[]) => execFileSync('git', a, { cwd: dir, encoding: 'utf8', env });
    git('init', '-q');
    git('config', 'user.email', 'test@example.com');
    git('config', 'user.name', 'test');
    git('add', '-A');
    git('commit', '-qm', 'init');
    execFileSync('npm', ['version', 'patch', '--no-git-tag-version'], { cwd: dir, stdio: 'pipe', env });

    const staged = git('diff', '--cached', '--name-only').split('\n').filter(Boolean).sort();
    expect(staged).toEqual(['package-lock.json', 'package.json', 'src/version.ts']);
    const stagedLock = JSON.parse(git('show', ':package-lock.json'));
    expect(stagedLock.version).toBe('1.2.4');
    expect(stagedLock.packages[''].version).toBe('1.2.4');
    expect(git('show', ':src/version.ts')).toBe(`${BANNER}export const VERSION = '1.2.4';\n`);
  });

  it('sync-version regenerates src/version.ts from package.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'uc-syncver-'));
    mkdirSync(join(dir, 'src'), { recursive: true });
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ version: '9.9.9' }));
    writeFileSync(join(dir, 'src/version.ts'), `export const VERSION = '0.0.0';\n`);
    execFileSync('node', [join(root, 'scripts/sync-version.mjs'), dir], { stdio: 'pipe' });
    expect(readFileSync(join(dir, 'src/version.ts'), 'utf8')).toBe(`${BANNER}export const VERSION = '9.9.9';\n`);
  });

  it('sync-version rejects a bad version and leaves src/version.ts untouched', () => {
    const dir = mkdtempSync(join(tmpdir(), 'uc-syncbad-'));
    mkdirSync(join(dir, 'src'), { recursive: true });
    const original = `export const VERSION = '0.0.0';\n`;
    writeFileSync(join(dir, 'src/version.ts'), original);
    for (const bad of [{}, { version: '1.2.3junk' }, { version: '01.2.3' }, { version: '1.2.3\n' }]) {
      writeFileSync(join(dir, 'package.json'), JSON.stringify(bad));
      let stderr = '';
      try {
        execFileSync('node', [join(root, 'scripts/sync-version.mjs'), dir], { stdio: 'pipe' });
      } catch (e) {
        stderr = String((e as { stderr?: unknown }).stderr ?? '');
      }
      expect(stderr, JSON.stringify(bad)).toMatch(/version missing or invalid/);
    }
    expect(readFileSync(join(dir, 'src/version.ts'), 'utf8')).toBe(original);
  });

  it('sync-version creates src/version.ts when missing, then is a byte-identical no-op', () => {
    const dir = mkdtempSync(join(tmpdir(), 'uc-syncnew-'));
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ version: '3.4.5' }));
    const target = join(dir, 'src/version.ts');
    // No src/ dir at all -> exercises the read-fails / mkdirSync-then-create branch.
    const out1 = execFileSync('node', [join(root, 'scripts/sync-version.mjs'), dir], { encoding: 'utf8' });
    expect(readFileSync(target, 'utf8')).toBe(`${BANNER}export const VERSION = '3.4.5';\n`);
    expect(out1).toMatch(/-> 3\.4\.5/);
    // Second run with the file already current -> no-op branch, no rewrite.
    const out2 = execFileSync('node', [join(root, 'scripts/sync-version.mjs'), dir], { encoding: 'utf8' });
    expect(readFileSync(target, 'utf8')).toBe(`${BANNER}export const VERSION = '3.4.5';\n`);
    expect(out2).toMatch(/already at 3\.4\.5/);
  });

  it('assertSemver accepts valid SemVer (returning it) and rejects the rest', () => {
    // Direct in-process cover of the guard shared by build-plugins + sync-version,
    // including its return value; the subprocess tests exercise the wiring.
    for (const v of ['0.1.2', '10.20.30', '1.2.3-alpha.1', '1.2.3-alpha.1+build.9']) {
      expect(assertSemver(v)).toBe(v);
    }
    for (const bad of ['', '1.2', '1.2.3junk', '01.2.3', '1.2.3-01', '1.2.3\n', undefined, null, ['1.2.3']]) {
      expect(() => assertSemver(bad as unknown as string), JSON.stringify(bad)).toThrow(/version missing or invalid/);
    }
  });

  it('rebuild wipes stale files from prior outputs', () => {
    expect(existsSync(join(root, 'dist-codex/STALE.txt'))).toBe(false);
    expect(existsSync(join(root, 'dist-qoder/STALE.txt'))).toBe(false);
  });

  it('build-plugins rejects a missing or non-SemVer package.json version', () => {
    const dir = mkdtempSync(join(tmpdir(), 'uc-badver-'));
    // Assert the guard's own message: the bare temp dir would make the script
    // throw ENOENT at the copy step even without the guard, so toThrow() alone
    // could green-pass with the guard deleted.
    const badVersions = [
      {},
      { version: '' },
      { version: null },
      { version: '1.2.3junk' },
      { version: ['1.2.3'] },
      { version: '01.2.3' },
      { version: '1.2.3-01' },
      { version: '1.2.3-alpha..1' },
      // JS '$' without the m flag anchors to end-of-input (not before a final
      // newline, unlike Perl/Python) — pinned here so that stays true.
      { version: '1.2.3\n' },
    ];
    for (const bad of badVersions) {
      writeFileSync(join(dir, 'package.json'), JSON.stringify(bad));
      let stderr = '';
      try {
        execFileSync('node', [join(root, 'scripts/build-plugins.mjs'), dir], { stdio: 'pipe' });
      } catch (e) {
        stderr = String((e as { stderr?: unknown }).stderr ?? '');
      }
      expect(stderr, JSON.stringify(bad)).toMatch(/version missing or invalid/);
    }
  });

  it('build-plugins accepts prerelease and build-metadata versions', () => {
    const dir = mkdtempSync(join(tmpdir(), 'uc-goodver-'));
    for (const version of ['10.20.30', '1.2.3-alpha.1', '1.2.3-alpha.1+build.9']) {
      writeFileSync(join(dir, 'package.json'), JSON.stringify({ version }));
      let stderr = '';
      try {
        execFileSync('node', [join(root, 'scripts/build-plugins.mjs'), dir], { stdio: 'pipe' });
      } catch (e) {
        stderr = String((e as { stderr?: unknown }).stderr ?? '');
      }
      // The bare temp root later fails at the copy step (ENOENT); all that
      // matters here is that an over-strict guard did not reject the version.
      expect(stderr, version).not.toMatch(/version missing or invalid/);
    }
  });

  it('bundled workflow copies are valid and portable', () => {
    for (const f of ['dist-qoder/workflows/uc-review.workflow.js', 'dist-qoder/workflows/uc-research.workflow.js']) {
      const src = readFileSync(join(root, f), 'utf8');
      expect(validateScript(src).ok).toBe(true);
      expect(lintWorkflowSource(src).filter((x) => x.level === 'error')).toEqual([]);
    }
  });
});

describe('parity demo assets', () => {
  it('sample repo has the planted-bug source and ground-truth doc', () => {
    expect(existsSync(join(root, 'examples/sample-repo/src/auth.js'))).toBe(true);
    expect(readFileSync(join(root, 'examples/sample-repo/PLANTED_BUGS.md'), 'utf8')).toMatch(/auth bypass/i);
  });

  it('committed parity output confirms both planted bugs (from a real Codex run)', () => {
    const output = JSON.parse(readFileSync(join(root, 'examples/parity-demo-output.json'), 'utf8'));
    expect(output.result.confirmed.length).toBeGreaterThanOrEqual(2);
    expect(output.agentCount).toBeGreaterThan(1);
  });

  it('assert-review.mjs passes on the committed parity output and fails on empty', () => {
    const script = join(root, 'examples/assert-review.mjs');
    // passes on the real output
    execFileSync('node', [script, join(root, 'examples/parity-demo-output.json')], { stdio: 'pipe' });

    // fails on an empty result
    const empty = join(mkdtempSync(join(tmpdir(), 'uc-assert-')), 'out.json');
    writeFileSync(empty, JSON.stringify({ result: { confirmed: [], report: 'nothing found' } }));
    expect(() => execFileSync('node', [script, empty], { stdio: 'pipe' })).toThrow();
  });
});
